<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2014  Stephan Kreutzer

This file is part of html2latex1.

html2latex1 is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License version 3 or any later version,
as published by the Free Software Foundation.

html2latex1 is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License 3 for more details.

You should have received a copy of the GNU General Public License
along with html2latex1. If not, see <http://www.gnu.org/licenses/>.
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns="http://www.w3.org/1999/xhtml" exclude-result-prefixes="xhtml">>
  <xsl:output method="text" encoding="UTF-8"/>
  
  <xsl:template match="xhtml:html">
    <xsl:text>\documentclass[a4paper]{memoir}&#xA;</xsl:text>
    <xsl:text>% This file was generated by layout1 for html2latex1 (https://github.com/skreutzer/automated_digital_publishing/).&#xA;</xsl:text>
    <xsl:text>&#xA;</xsl:text>
    <xsl:text>\usepackage[utf8]{inputenc}&#xA;</xsl:text>
    <xsl:text>\usepackage{ngerman}&#xA;</xsl:text>
    <xsl:text>\usepackage{url}&#xA;</xsl:text>
    <xsl:text>&#xA;</xsl:text>
    <xsl:text>\setlength{\parskip}{0pt}&#xA;</xsl:text>
    <xsl:text>
\renewcommand*{\maketitle}{%
  \thispagestyle{empty}
  \begingroup%
    \vspace*{\baselineskip}
    \vfill
    \hbox{%
      \vbox{%
        \vspace{0.1\textheight}
        {\noindent\HUGE\bfseries\centering </xsl:text>
        <xsl:value-of select="xhtml:head/xhtml:title//text()"/>
        <xsl:text>\par}\vspace*{5\baselineskip}&#xA;</xsl:text>
        <xsl:if test="xhtml:head/xhtml:meta[@name='author']">
          <xsl:text>        {\Large\centering </xsl:text>
          <xsl:value-of select="xhtml:head/xhtml:meta[@name='author']/@content"/>
          <xsl:text>\par}&#xA;</xsl:text>
        </xsl:if>
        <xsl:text>        \vspace{0.35\textheight}</xsl:text>
        <xsl:if test="xhtml:head/xhtml:meta[@name='publisher']">
          <xsl:text>&#xA;        {\noindent\centering </xsl:text>
          <xsl:value-of select="xhtml:head/xhtml:meta[@name='publisher']/@content"/>
          <xsl:text>\par}</xsl:text>
        </xsl:if>
        <xsl:text> 
      }%
    }%
    \vfill
    \null
  \endgroup%
  \pagebreak{}
  \newpage{}
  \thispagestyle{empty}
  \mbox{}
  \pagebreak{}
}
    </xsl:text>
    <xsl:text>&#xA;</xsl:text>
    <xsl:text>\begin{document}&#xA;</xsl:text>
    <xsl:text>\frontmatter&#xA;</xsl:text>
    <xsl:text>\maketitle&#xA;</xsl:text>
    <xsl:text>\tableofcontents&#xA;</xsl:text>
    <xsl:text>\mainmatter&#xA;</xsl:text>
    <xsl:apply-templates select="xhtml:body"/>
    <xsl:text>\end{document}&#xA;</xsl:text>
  </xsl:template>

  <xsl:template match="xhtml:html/xhtml:body/xhtml:div">
    <xsl:choose>
      <xsl:when test="xhtml:h1">
        <xsl:text>\part{</xsl:text>
        <xsl:value-of select="xhtml:h1"/>
        <xsl:text>}&#xA;</xsl:text>
      </xsl:when>
      <xsl:when test="xhtml:h2">
        <xsl:text>\chapter{</xsl:text>
        <xsl:value-of select="xhtml:h2"/>
        <xsl:text>}&#xA;</xsl:text>
      </xsl:when>
    </xsl:choose>
    <xsl:apply-templates/>
  </xsl:template>
  <xsl:template match="xhtml:html/xhtml:body/xhtml:div/xhtml:p[@class='paragraph_default']">
    <xsl:if test="../xhtml:h2">
      <xsl:for-each select="text()">
        <xsl:value-of select="."/>
      </xsl:for-each>
      <xsl:text>&#xA;&#xA;</xsl:text>
    </xsl:if>
  </xsl:template>

  <xsl:template match="xhtml:html/xhtml:body/xhtml:div/xhtml:div">
    <xsl:choose>
      <xsl:when test="xhtml:h2">
        <xsl:text>\chapter{</xsl:text>
        <xsl:value-of select="xhtml:h2"/>
        <xsl:text>}&#xA;</xsl:text>
      </xsl:when>
      <xsl:when test="xhtml:h3">
        <xsl:text>\section{</xsl:text>
        <xsl:value-of select="xhtml:h3"/>
        <xsl:text>}&#xA;</xsl:text>
      </xsl:when>
    </xsl:choose>
    <xsl:apply-templates/>
  </xsl:template>
  <xsl:template match="xhtml:html/xhtml:body/xhtml:div/xhtml:div/xhtml:p[@class='paragraph_default']">
    <xsl:apply-templates/>
    <xsl:text>&#xA;&#xA;</xsl:text>
  </xsl:template>
  <xsl:template match="xhtml:html/xhtml:body/xhtml:div/xhtml:div/xhtml:p[@class='paragraph_default']//text()">
    <xsl:value-of select="."/>
  </xsl:template>
  
  <xsl:template match="xhtml:html/xhtml:body/xhtml:div/xhtml:div/xhtml:div">
    <xsl:choose>
      <xsl:when test="xhtml:h3">
        <xsl:text>\section{</xsl:text>
        <xsl:value-of select="xhtml:h3"/>
        <xsl:text>}&#xA;</xsl:text>
      </xsl:when>
      <xsl:when test="xhtml:h4">
        <xsl:text>\subsection{</xsl:text>
        <xsl:value-of select="xhtml:h4"/>
        <xsl:text>}&#xA;</xsl:text>
      </xsl:when>
    </xsl:choose>
    <xsl:apply-templates/>
  </xsl:template>
  <xsl:template match="xhtml:html/xhtml:body/xhtml:div/xhtml:div/xhtml:div/xhtml:p[@class='paragraph_default']">
    <xsl:apply-templates/>
    <xsl:text>&#xA;&#xA;</xsl:text>
  </xsl:template>
  <xsl:template match="xhtml:html/xhtml:body/xhtml:div/xhtml:div/xhtml:div/xhtml:p[@class='paragraph_default']//text()">
    <xsl:value-of select="."/>
  </xsl:template>

  <xsl:template match="xhtml:html/xhtml:body/xhtml:div/xhtml:div/xhtml:div/xhtml:div">
    <xsl:if test="xhtml:h4">
      <xsl:text>\subsection{</xsl:text>
      <xsl:value-of select="xhtml:h4"/>
      <xsl:text>}&#xA;</xsl:text>
    </xsl:if>
    <xsl:apply-templates/>
  </xsl:template>
  <xsl:template match="xhtml:html/xhtml:body/xhtml:div/xhtml:div/xhtml:div/xhtml:div/xhtml:p[@class='paragraph_default']">
    <xsl:apply-templates/>
    <xsl:text>&#xA;&#xA;</xsl:text>
  </xsl:template>
  <xsl:template match="xhtml:html/xhtml:body/xhtml:div/xhtml:div/xhtml:div/xhtml:div/xhtml:p[@class='paragraph_default']//text()">
    <xsl:value-of select="."/>
  </xsl:template>
  
  <xsl:template match="xhtml:a">
    <xsl:for-each select="text()|*/text()">
      <xsl:value-of select="."/>
    </xsl:for-each>
    <xsl:text>\footnote{\url{</xsl:text><xsl:value-of select="@href"/><xsl:text>}}</xsl:text>
  </xsl:template>

  <xsl:template match="text()|@*"/>

</xsl:stylesheet>
