# Copyright (C) 2015  Stephan Kreutzer
#
# This file is part of bommanager1.
#
# bommanager1 is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License version 3 or any later version,
# as published by the Free Software Foundation.
#
# bommanager1 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License 3 for more details.
#
# You should have received a copy of the GNU Affero General Public License 3
# along with bommanager1. If not, see <http://www.gnu.org/licenses/>.



.PHONY: bommanager1 clean



bommanager1: bommanager1.class

bommanager1.class: bommanager1.java
	javac bommanager1.java

clean:
	rm -f bommanager1.class

