<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2014-2015  Stephan Kreutzer

This file is part of template1 for odt2html.

template1 for odt2html is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License version 3 or any later version,
as published by the Free Software Foundation.

template1 for odt2html is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License 3 for more details.

You should have received a copy of the GNU Affero General Public License 3
along with template1 for odt2html. If not, see <http://www.gnu.org/licenses/>.
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="xml" version="1.0" encoding="UTF-8" indent="yes" doctype-public="-//W3C//DTD XHTML 1.0 Strict//EN" doctype-system="http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"/>

  <xsl:template match="div[@class='part']">
    <xsl:comment> This file was generated by html2epub1_html_part.xsl of template1 for odt2html, which is free software licensed under the GNU Affero General Public License 3 or any later version (see https://github.com/publishing-systems/automated_digital_publishing/ and http://www.publishing-systems.org). </xsl:comment><xsl:text>&#xA;</xsl:text>
    <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
      <head>
        <title>
          <xsl:if test="h1">
            <xsl:for-each select="h1/text()">
              <xsl:value-of select="."/>
            </xsl:for-each>
          </xsl:if>
        </title>
      </head>
      <body>
        <div class="part">
          <xsl:if test="h1">
            <h1>
              <xsl:for-each select="h1/text()">
                <xsl:value-of select="."/>
              </xsl:for-each>
            </h1>
          </xsl:if>
        </div>
      </body>
    </html>
  </xsl:template>

  <xsl:template match="text()|@*"/>

</xsl:stylesheet>
