# Copyright (C) 2014  Stephan Kreutzer
#
# This file is part of txtreplace1.
#
# txtreplace1 is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License version 3 or any later version,
# as published by the Free Software Foundation.
#
# txtreplace1 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License 3 for more details.
#
# You should have received a copy of the GNU Affero General Public License 3
# along with txtreplace1. If not, see <http://www.gnu.org/licenses/>.



.PHONY: txtreplace1 clean



txtreplace1: txtreplace1.class

txtreplace1.class: txtreplace1.java
	javac txtreplace1.java

clean:
	rm -f txtreplace1.class

